### ISSUE TITLE
Mention the requirement for "network manager" for skywire to run in documentation

### ISSUE THREAD

**Issue by ADepic** [Skyfleet/sky-update#1]
EDIT: This error goes away if you install `network manager`. This should be in the documentation. It seems to be related to raspberry pi
```
/usr/bin/skywire-startup: line 60: nmcli: command not found
Current IP address for connection skynet: 
Deleting all nm connections...
/usr/bin/skywire-startup: line 72: nmcli: command not found
Setting up nm connection skynet...
/usr/bin/skywire-startup: line 78: nmcli: command not found
/usr/bin/skywire-startup: line 79: nmcli: command not found

```

**Comment by ADepic** [comment]
seems like this problem goes if you install `network-manager` (via `sudo apt-get install network-manager`)

but then this error came up: 
```
Error: skynet - no such connection profile.
Current IP address for connection skynet: 
Deleting all nm connections...
Connection 'eth0' (27bbaa20-9a03-47ed-a154-7a0f5fc06c68) successfully deleted.
Setting up nm connection skynet...
Error: failed to modify ipv4.addresses: invalid IP address: Invalid IPv4 address '?00000000000000000000ffffc0a801'.
Error: unknown connection 'skynet'.
```

**Comment by 0pcom** [comment]
Things are changing in the sources. With the next release there will be a hypervisor and visor systemd service included in the package.

I was going to list networkmanager as a dependancy but I think it's better if the skybian-firstrun (formerly skywire-startup) script was included in a separate package, networkmanager is a dependancy for that script.

I'm awaiiting my PR to be approved here
https://github.com/SkycoinProject/skywire-mainnet/pull/355

which adds a package directive to the Makefile for skywire-mainnet.

The rest will be sorted out soon enough, I'm trying to get the package repository to be maintained within the skycoinproject.

**Comment by ADepic** [comment]
Is this still a requirement?

**Comment by 0pcom** [comment]
> Is this still a requirement?

look at the [skybian-firstrun](https://github.com/SkycoinProject/skybian/blob/master/static/skybian-firstrun) script
lines 66 71 and 74 still call `nmcli` but I'm not sure of the significance besides setting a static ip if one has not aalready been set.

I've observed archlinuxARM images which were processed by skyimager switch immediately from dhcp to a static ip when I ran the skybian-firstrun service, but it's not explicitly necessary to have a static IP at all for skywire to work. It' merely done that way to have a preditable ip address to access the visors / nodes at.

In theory you can skip the part of your guide which talks about setting a static ip if you use skyimager to process the image.

I'm trying to come up with a solid workaround for having to use skyimager to accomplish the configuration of the hypervisor public key in the visor's config file. Since the skybian-firstrun script is reliant on that, I'm not really trying to figure it out at this point.

I will be sure in futue packages cntaining this script that anything like this gets listed as a dependancy which will be automatically installed when you install the package.
